title: DevQuest
description: Driven to Elevate Visions through a quest of innovation, creation, and exploration.
remote_theme: just-the-docs/just-the-docs

# Optional extras for customization
color_scheme: light
logo: /assets/images/devquest-logo.png
search_enabled: true
heading_anchors: true



# Theme setup
remote_theme: just-the-docs/just-the-docs

# Optional customization
color_scheme: light
logo: /assets/images/devquest-logo.png
search_enabled: true
heading_anchors: true

# Load custom SCSS
sass:
  style: compressed

# Include custom CSS
just_the_docs:
  custom_css:
    - /assets/css/custom.scss
